server:
  port: 80                                # port to listen on
  baseURL: "/"                            # base URL for the server, the subpath that the server is running on.
  logging:
    - levels: "info|warning|error"        # separated list of log levels to enable. (eg. "info|warning|error|debug")  
  database: "data/database.db"            # path to the database file
  sources:                                # validate:required,dive  validate:required,dive
    - path: "/srv/users"                  # validate:required
      name: "My Files"
      config:        
        defaultUserScope: "/"
        defaultEnabled: true
        createUserDir: true
  externalUrl: ""                         # used by share links if set (eg. http://mydomain.com)
  internalUrl: ""                         # used by integrations if set, this is the base domain that an integration service will use to communicate with filebrowser (eg. http://localhost:8080)
  cacheDir: "data/tmp"                    # path to the cache directory, used for thumbnails and other cached files  
auth:
  adminUsername: "admin"                  # secret: the username of the admin user. If not set, the default is "admin".
  adminPassword: "admin"                  # secret: the password of the admin user. If not set, the default is "admin".  
frontend:
  name: "FileBrowser Quantum"             # display name
integrations:
  office:                                 # validate:omitempty  validate:omitempty
    url: ""                               # The URL to the OnlyOffice Document Server, needs to be accessible to the user.  validate:required  validate:required
    internalUrl: ""                       # An optional internal address that the filebrowser server can use to communicate with the OnlyOffice Document Server, could be useful to bypass proxy.
  media:                                  # validate:omitempty  validate:omitempty    
    convert:                              # config for ffmpeg conversion settings
      imagePreview:                       # supported image preview formats. defaults to false for all types unless explicitly enabled.
        heic: true